### PR TITLE
Format on Save

### LINKED ISSUE #81: format on save
The format on save action seems to not work... However, ctrl+shift+f works. Would be nice to have the same functionality automatically on save.

### PR DESCRIPTION
**Pull request by lorenzodallavecchia**
Closes #81.

### CODE REVIEW

**Comment by angelozerr** [comment]
Great PR @lorenzodallavecchia!

Please note thisat tsserver seems providing capability to format "on key". I think we should investigate too this feature (I think that VSCode uses it).

**Comment by lorenzodallavecchia** [comment]
> Please note thisat tsserver seems providing capability to format "on key"

I had spotted that one in protocol.d.ts, but did not know whether you were already using it or not (now I assume not!).

I may look into that later, especially since I want to track down a strange bug that causes nothing to happen when presseing Enter from within two braces: really annoying.

**Comment by angelozerr** [comment]
@lorenzodallavecchia see https://github.com/angelozerr/typescript.java/issues/146

**Comment by angelozerr** [comment]
> I may look into that later, especially since I want to track down a strange bug that causes nothing to happen when presseing Enter from within two braces: really annoying.

Could you create an issue for that please.

**Comment by angelozerr** [comment]
>  may look into that later, especially since I want to track down a strange bug that causes nothing to happen when presseing Enter from within two braces: really annoying.

Is it https://github.com/angelozerr/typescript.java/issues/72 ?

**Comment by lorenzodallavecchia** [comment]
> Could you create an issue for that please.
> Is it #72 ?

No, it is not #72.
I will surely create an issue: I just need to find a consistent way to reproduce it.

**Comment by lorenzodallavecchia** [comment]
Ok I found out what was causing that other problem. I reported and closed it (#150) so it remains for future reference.

**Pull request merged**
